### ISSUE TITLE
Used pandas.core.ops attribute does not appear to exist

### ISSUE THREAD

**Issue by PrinceWalnut** [rs-station/reciprocalspaceship#227] opened 2023-09-25 21:46 UTC
Was running a `careless` script when the following (abridged) error occurred:

```
  File "/net/holy-nfsisilon/ifs/rc_labs/hekstra_lab/people/rahewitt/opt/anaconda/envs/test/lib/python3.11/site-packages/reciprocalspaceship/dtypes/internals.py", line 398, in __array_ufunc__
    result = ops.maybe_dispatch_ufunc_to_dunder_op(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pandas.core.ops' has no attribute 'maybe_dispatch_ufunc_to_dunder_op'
```

Perhaps a move in a new version of `pandas`.

**Comment by JBGreisman** [comment] 2023-09-25 21:48
Do you mind confirming the `pandas` and `rs` versions? That will help me track down what's going on here

**Comment by PrinceWalnut** [comment] 2023-09-25 22:28
The versions are as follows:

`reciprocalspaceship: 1.0.1`
`pandas: 2.0.3`

Note: upgrading to `pandas==2.1.1` appears to have fixed the issue.

**Comment by JBGreisman** [comment] 2023-10-09 21:28
Sorry for the delay, but looking into this it does seem that `pandas v2.0.3` has relevant method/namespace:

```
In [1]: import pandas as pd

In [2]: pd.__version__
Out[2]: '2.0.3'

In [3]: from pandas.core import ops

In [4]: ops.maybe_dispatch_ufunc_to_dunder_op?
Docstring:
Dispatch a ufunc to the equivalent dunder method.

Parameters
----------
self : ArrayLike
    The array whose dunder method we dispatch to
ufunc : Callable
    A NumPy ufunc
method : {'reduce', 'accumulate', 'reduceat', 'outer', 'at', '__call__'}
inputs : ArrayLike
    The input arrays.
kwargs : Any
    The additional keyword arguments, e.g. ``out``.

Returns
-------
result : Any
    The result of applying the ufunc
Type:      builtin_function_or_method
```
Do you mind including more details of the traceback and a minimal example? I don't seem to be able to reproduce this locally with `rs v1.0.1` and `pandas v2.0.3`.

**Comment by JBGreisman** [comment] 2023-11-04 01:13
I'm going to close this issue because I can't reproduce it, but please reopen if you run into any more troubles that seem like this.

**Closed by JBGreisman** 2023-11-04 01:13 UTC
